version: "3.2"
services:
  jupyter:
    image: agh/supermodeling
    container_name: supermodeling
    volumes:
      - type: "bind"
        source: .
        target: /usr/local/lib/supermodeling/
    ports:
      - 8888:8888
